services:
  db:
    image: postgres:16-alpine
    container_name: uni-postgres
    environment:
      POSTGRES_DB: universidade
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d universidade"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: uni-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/universidade
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: universidade-secret-key-muito-segura-para-desenvolvimento-v1-2026
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: uni-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  pgdata:
